Added sections on the landing page
bundly/dash pull request #51
Opened 2020-08-18 17:55 UTC by NB134

Added Features, About and Contribute Sections on the landing page
All the content was taken from readme.md, needs review.
Working Demo link:  https://dash-three.vercel.app/.
Kindly Review the Design and Content of the Added Sections.

2020-08-19 10:21 UTC, kartikcho requested changes
Hi, thanks for working on this!

I see some assets that have been added but not used, could you remove them from the PR?

Run both the files through a formatter like Pretttier to have consistent formatting, also remove comments from `login.js`.

Good work!

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +
nit: extra committed line.

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +  // background: url(https://i.giphy.com/media/l0iVAuEtPF5KRbqmvd/source.gif);
Could you remove this since we've agreed on having our logo on landing.

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +
nit: A lot of extra lines seems to have been committed, could you run the file through a basic formatter?

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +// Landing Page Sections CSS
Could you remove these lines 303-304.

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +  .Features
Let's ensure all classes use small case and hyphens for naming. Change this to `features` and same for other affected classes.

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +  .TextContainer{
same here as above, use hyphens to make it `text-container`

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +.Contri{
Could you rename this to `contribute`, would be more easy to understand.

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +.ContriButton{
Similarly here, `contribute-button` or `contribute-btn`

2020-08-19 10:21 UTC, kartikcho commented on src/scss/login.module.scss
> +  .AboutUs > .GifCard > img{
There is no About Us section on the page so let's make this `about` or something similar. Same for the comment on 383.

2020-08-19 10:21 UTC, kartikcho commented on src/views/pages/login/Login.js
> +{/* Features Section */}
Let's remove these comments and run this file through a formatter too.

2020-08-19 10:22 UTC, kartikcho commented
Requesting a review from @sauravhiremath to review page content and check the code in general.

2020-08-19 13:47 UTC, NB134 commented
I ran prettier and removed unused assets from old commits.

2020-08-19 19:06 UTC, sauravhiremath reviewed
That's some solid work!

There are a few changes though
* Remove the styled CSS import and just use:
```javascript
import '/theme/login.scss'
```
* Add escape characters for the latitudes and longitudes

I am mentioning them as bullet points here, as all the changes right now are being migrated to [bundly/dash-beta](https://github.com/bundly/dash-beta).

If possible could you open the PR with the same changes on the `dash-beta` repo? It should be relatively easier to import these changes as the files structure are very similar, and we can help you out if needed during migration.

Anyway, this is awesome work!

2020-08-20 03:57 UTC, NB134 commented
So, i need to remove the styled css import and import the css normally, changing the className value from {styled.class} to "class".
Also i have added latitudes and longitudes using content property of the pseudo element so should i change it entirely into unicode or only spaces in unicode.

2020-08-20 07:44 UTC, sauravhiremath commented
1. Yeah, just importing CSS as you mentioned
2. Just the apostrophes and degrees in Unicode, like `&quot;`, `&apos;` and `&deg;`. No need to encode `spaces`

2020-08-21 12:42 UTC, closed without merging